print("Введите первое число")
a = int(input())
print("Введите второе число")
b = int(input())

print(a, "+", b, "=", a+b)
print(a, "-", b, "=", a-b)
print(b, "-", a, "=", b-a)
print(a, "*", b, "=", a*b)
print(a, "/", b, "=", a/b)
print(b, "/", a, "=", b/a)
print(a, "^", b, "=", a**b)
print(b, "^", a, "=", b**a)
